version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    networks:
      - inception
    volumes:
      - ../../data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - ../../data/mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - ../../data/wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fle-tolg/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fle-tolg/data/mariadb'

networks:
  inception:
    driver: bridge
