version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx_img
    env_file: .env
    networks:
      - inception
    volumes:
      - /home/fle-tolg/data/wordpress:/var/www/wordpress/
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb_img
    env_file: .env
    networks:
      - inception
    volumes:
      - /home/fle-tolg/data/mariadb:/var/lib/mysql/
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress_img
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /home/fle-tolg/data/wordpress:/var/www/wordpress/
    networks:
      - inception
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fle-tolg/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fle-tolg/data/mariadb'

networks:
  inception:
    driver: bridge
