version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
        #    context: requirements/mariadb
      #    dockerfile: Dockerfile
    restart: always
    expose:
      - "3306"

  nginx:
    build: requirements/nginx/
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
        #    context: requirements/nginx
      #    dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
        #    context: requirements/wordpress
      #    dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
      #    driver_opts:
      #    type: 'none'
      #    o: 'bind'
      #    device: '/Users/fle-tolg/data/wordpress'
  mariadb:
    driver: local
      #    driver_opts:
      #    type: 'none'
      #    o: 'bind'
      #    device: '/Users/fle-tolg/data/mariadb'

networks:
  inception:
    driver: bridge


#version: '3'

  #services: #all containers that will be created
  #db: #name
  #image: mysql:5.7 #the image + version
  # volumes: #store the data at the dir
  #   - db_data:/var/lib/mysql
  # restart: always #is the container crash, it will restart
  # environment: #env that are need by mysql to work
  #   MYSQL_ROOT_PASSWORD: wordpress
  #   MYSQL_DATABASE: wordpress
  #   MYSQL_USER: wordpress
  #   MYSQL_PASSWORD: wordpress

  #  wordpress:
  # depends_on: #dependance
  #   - db
  # image: wordpress:latest
  # ports: #which port to use
  #   - "8000:80"
  # restart: always
  # environment:
  #   WORDPRESS_DB_HOST: db:3306
  #   WORDPRESS_DB_USER: wordpress
  #   WORDPRESS_DB_PASSWORD: wordpress
  #      WORDPRESS_DB_NAME: wordpress

        #volumes:
  #db_data: {}
  
