version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    build: requirements/nginx/
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
      #    driver_opts:
      #    type: 'none'
      #    o: 'bind'
      #    device: '/Users/fle-tolg/data/wordpress'
  mariadb:
    driver: local
      #    driver_opts:
      #    type: 'none'
      #    o: 'bind'
      #    device: '/Users/fle-tolg/data/mariadb'

networks:
  inception:
    driver: bridge
